### ISSUE TITLE
Django: No module named google.protobuf

### ISSUE THREAD

**Issue by lucastockmann** [emeth-/pokelocater#11]
After installing, migrating and running I got these error on http://127.0.0.1:8000/

> ImportError at /
> No module named google.protobuf
> Request Method:   GET
> Request URL:  http://127.0.0.1:8000/
> Django Version:   1.8
> Exception Type:   ImportError
> Exception Value:  
> No module named google.protobuf

This is what the command line looks like:

> python manage.py runserver
> Performing system checks...
> 
> System check identified no issues (0 silenced).
> July 18, 2016 - 11:19:21
> Django version 1.8, using settings 'hackathon.settings'
> Starting development server at http://127.0.0.1:8000/
> Quit the server with CONTROL-C.
> [18/Jul/2016 11:19:24]"GET / HTTP/1.1" 500 112033

**Comment by emeth-** [comment]
Were you able to install the dependencies in requirements.txt?

```
sudo pip install -r requirements.txt
```

**Comment by emeth-** [comment]
Going to close this issue and peg it as needing to install requirements as per last comment, feel free to re-open if that wasn't the case!

**Comment by lucastockmann** [comment]
I did install the dependencies. (`sudo pip install -r requirements.txt`)

To resolve this issue I had to install protobuf on my own.
https://github.com/google/protobuf/tree/master/python#installation

**Comment by emeth-** [comment]
@lucastockmann Thanks for the update!
