### ISSUE TITLE
Prefer Google Login over PTC

### ISSUE THREAD

**Issue by joshfarrant** [emeth-/pokelocater#13]
It might be worth adding an option to prefer log in with Google over PTC, as it's generally more stable.

**Comment by MostlyPride** [comment]
I would also enjoy this too, at the current time putting in fake ptc info, does not seem to allow the application to use gmail as the defaulted method.

**Comment by emeth-** [comment]
I just pushed a lot of new code - the google auth should be respected appropriately now, all you have to do is leave the PTC auth credentials to blanks/fake/whatever their default value is (just ignore them).

I'm personally satisfied with that
