### ISSUE TITLE
Try deploying it but I get an error

### ISSUE THREAD

**Issue by kingeddard** [emeth-/pokelocater#15]
Invalid template repository.

**Comment by kingeddard** [comment]
"The source could not be retrieved"

**Comment by kingeddard** [comment]
Used the deploy to heroku button in the readme

**Comment by schlegp** [comment]
Same error for me. Repository seems not to be configured correctly. Sadly not able to deploy to heroku from mobile anymore.

**Comment by emeth-** [comment]
Pushed an update that sets the template directory a different way, and then tested the heroku deploy and it works for me now.

Thanks for notifying me about this!
