### ISSUE TITLE
Error while fetching get_poke

### ISSUE THREAD

**Issue by danielyeriksson** [emeth-/pokelocater#16]
Traceback:
File "/app/.heroku/python/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
1.                     response = wrapped_callback(request, _callback_args, *_callback_kwargs)
   File "/app/api/views.py" in get_poke
2.     result = pokelocator_api.main(location=location, direction=direction)
   File "/app/api/pokelocator_api.py" in main
3.             access_token = login_google(goog_username, goog_password)
   File "/app/api/pokelocator_api.py" in login_google
4.     fourth=r2.history[len(r2.history)-1].headers['Location'].replace('amp%3B','').replace('amp;','')

Deployed to Heroku manually and all variables are set.

**Comment by emeth-** [comment]
@clearminds This looks like it's a pokemongo server issue, if you try again later/now does the issue persist?

**Comment by danielyeriksson** [comment]
The game works fine on the phone, anything else I can do to test if it's the server?

**Comment by danielyeriksson** [comment]
Also tried with a brand new google account now - the old one seemed to have some kind of lockout. But same issue with this one

**Comment by danielyeriksson** [comment]
Google Issue - fixed

**Comment by ClintOxx** [comment]
@clearminds what did you do to fix the issue, currently having the same problem

**Comment by danielyeriksson** [comment]
@Clintoxen answered googles emails regarding login attempts

**Comment by ClintOxx** [comment]
@clearminds huh thats weird i tried doing the same and get_poke keeps failing, wonder if it may just be PoGo server issues since it seems to be having trouble using my PTC account too. Thanks

**Comment by ClintOxx** [comment]
Yea its pogo's servers being shitty thanks for the help. This should help anyone having problems with google blocking https://accounts.google.com/b/0/DisplayUnlockCaptcha
