### ISSUE TITLE
No longer working, was working last night (July 18th 2016)

### ISSUE THREAD

**Issue by SophisticaSean** [emeth-/pokelocater#23]
Now I'm just getting 500's, POST /get_poke HTTP/1.1" 500 9137. It never loads any pokemon. Anything changed that I need to change on my end too?

**Comment by SophisticaSean** [comment]
It loads pokemon thru the console, 

(46) Paras is visible at (40.6254649854, -111.855973572) for 789 seconds (220m NE from you)
(10) Caterpie is visible at (40.6256662942, -111.854576233) for 385 seconds (286m NE from you)

but they never populate on the map :(

**Comment by John758364** [comment]
I am getting a similar error, I am unable to even load them in the terminal

**Comment by capito-tar-gz** [comment]
I don't see any results in the console or map, either.

**Comment by SoulDemon** [comment]
You guys... china was released  servers are down.

**Comment by emeth-** [comment]
^What he said, the pokemon go server/api is down right now.

**Comment by SophisticaSean** [comment]
Odd. Because I can totes hit the API from other applications and get it to work, but it doesn't want to work with this one. I'll check back in later. Been watching this to see if pokemon is up or not: http://ispokemongodownornot.com/

**Comment by SoulDemon** [comment]
Your other api has a stored json of previous pokemon fetched..

**Comment by TeeYum** [comment]
Would the above also cause [BAD CACHE] to come up in papertrail followed by being unable to authenticate? 
EDIT: Almost certain that after a few failed logins and 503's the account gets disabled, and then that gets cached and causes the above. Not sure there's a solution better than the servers becoming more stable :)

**Comment by Enyxx** [comment]
Same issue here.
Exact same logs as TeeYum.
It also blocks the accs for too much failed try

**Comment by ic3guy** [comment]
For some reason my PTC account had to be "verified", even though it was working for the past few days. This has gotten it to work again in some capacity. I'll say it is probably the servers crapping out because of China.

**Comment by fu20161234** [comment]
Are you guys still having this issue? Still getting "jquery.min.js:4 POST https://[redacted].herokuapp.com/get_poke 500 (INTERNAL SERVER ERROR)" but I can get in the game fine and another tool works from the command line.

**Comment by tristan-hyams** [comment]
At this point, I anticipate if Herokuapps.com domain has been blocked.  Is anyone's working?

In game works, treesimulation is 500 response, tried 3 different accounts.

Again, @emeth- appreciate all the work as well as others.

I was only interested in this one project because it wasn't really a cheat/hack.  In game tracker has been broken a while.  Lost 3 Pikachus... still don't have Pikachu because of that -.-

**Comment by onepiece10** [comment]
I have the same problem as SophisticaSean. I look thru the logs file:

`2016-07-20T18:44:02.274070+00:00 app[web.1]: Within one step of LatLng: 45.6512258266,-73.7917939065 (264m SE from you)`

but it's not populating the map.

**Comment by fu20161234** [comment]
Well then you're getting a lot farther than I am... hm...

**Comment by onepiece10** [comment]
I suggest using this for the time being, if anyone wants to go for some pokemon hunting

https://github.com/AHAAAAAAA/PokemonGo-Map

**Comment by TeeYum** [comment]
This still works just fine provided that the pgo services are actually up :)

**Comment by tristan-hyams** [comment]
Can confirm, working for me as well, although I am using a fork.

**Comment by SophisticaSean** [comment]
Most recent version seems to have fixed the problem I was having. Now this is working well! Thanks. :)
