### ISSUE TITLE
Can't set it up locally. Won't login with RPC and is Google working?

### ISSUE THREAD

**Issue by Maufeat** [emeth-/pokelocater#3]
Hey,

I tried to set that project up locally, since I can't use Heroku, faced one issue, it can't login to RPC:

> api_req: login_type ptc
> Sleeping for 2 seconds to get around rate-limit.
> BAD CACHE
> [!] login for: Invalid
> access_token None
> [-] Trouble logging in via PTC
> [+] Authentication with google...
> [17/Jul/2016 18:59:57]"POST /get_poke HTTP/1.1" 500 10891

does it even try to login with google? Can I switch? Thank you!

"[!]login for: Invalid" <- on other python scripts with the API it says "[!]login for: username" don't know why here Invalid.

**Comment by emeth-** [comment]
@Maufeat It looks like the script is unable to read from your environmental variables. 

I just realized I forgot to put in that step for setting it up locally. I updated to readme to reflect it.

The specific step is this:

### Setup environmental variables (google how to do it for your system):

```
PTC_USERNAME=my_pokeclub_username
PTC_PASSWORD=my_pokeclub_password
GOOG_USERNAME=my_google_username
GOOG_PASSWORD=my_google_password
```

**Comment by Maufeat** [comment]
Done this one, but does not work. I use Windows 10 with python version 2.7.12, installed everything from requirements.txt

But I just replaced the "os.environ.get('xxx', 'Invalid')" with my values, that work. But still can't get an error:

> [+] Login successful
> [+] Username: xxx
> [+] You are playing Pokemon Go since: 2016-07-17 01:XX:XX
> [+] POKECOIN: 0
> [+] STARDUST: 0
> Sleeping for 2 seconds to get around rate-limit.
> [17/Jul/2016 19:45:51]"POST /get_poke HTTP/1.1" 500 10884

EDIT: Was able to see Pokemons, look like it worked. But now again only errors.
