### ISSUE TITLE
how to set a gps position

### ISSUE THREAD

**Issue by equals215** [emeth-/pokelocater#35]
I'm wondering how to set precise gps coordinates because location isn't working

**Comment by TeeYum** [comment]
You will need to manually edit the query for coordinates and instead replace them (and the query return) with the desired location. This appears to be more of a feature request than a bug/issue.

**Comment by equals215** [comment]
But where do I edit the querry? Cause il dont understand very much this script

**Comment by HDBear** [comment]
Just use fake GPS on your android and open the app via Firefox. Works fine then
