### ISSUE TITLE
please use new login for google

### ISSUE THREAD

**Issue by Mila432** [emeth-/pokelocater#4]
https://github.com/Mila432/Pokemon_Go_API/blob/master/login.py#L34
i changed the function , some users were saying it failed for them

**Comment by emeth-** [comment]
@Mila432 Thanks for dropping by!

I ran a quick diff on the code you linked vs what I have active (with a minor tweak of renaming a variable to clean up the diff)

https://www.diffchecker.com/fuq7atu5

Only thing I notice different is the unicode character, which my code editor dropped, so I think I must have pulled your latest earlier.

**Comment by Mila432** [comment]
@emeth- thanks , it was a mistake this line was important:
fourth=r2.history[len(r2.history)-1]...
