### ISSUE TITLE
Pokemon Training Club Account - 500 Errors

### ISSUE THREAD

**Issue by eratik** [emeth-/pokelocater#5]
Hey guys,

The PTC account has stopped taking new accounts at the moment.  Is the PTC account a dependency even if you can login with your google account?  I just seeded with a non-existent PTC account and assumed it would fail back to my google account.  Getting a 500 on /get_poke.  Directly before that it says trouble logging in via PTC so looks like I'm not assuming correct. ;)

**Comment by XeroAura** [comment]
Refresh the PTC account registration page a few times, and it'll usually open up.

**Comment by emeth-** [comment]
@eratik If you don't input a PTC account (or give it a fake one), it should/will fall back to your google one just fine (I tested it locally now to make sure)

**Comment by eratik** [comment]
Thanks guys, appreciate the quick reply! XeroAura, I tried refreshing the registration screen a ton of times and it finally opened up.  For anyone else without the PTC account that worked.  Emeth, thanks I was digging through code and that was going to be what I tried next.  Thanks again.  Great work.  This is pretty cool.

**Comment by ngunia** [comment]
@emeth-  I was trying to get the google login to work and could not on heroku. Worked perfectly fine locally, but not when deployed. I didn't debug too deeply, but `login_google()` never returns in main.  Could have something to do with access control maybe?

**Comment by emeth-** [comment]
@ngunia I'll check it out later today when I get home from work.

I do see login_google() returning an access token here:
https://github.com/emeth-/pokelocater/blob/master/api/pokelocator_api.py#L253

Which is picked up here:
https://github.com/emeth-/pokelocater/blob/master/api/pokelocator_api.py#L361

And google login was working for me yesterday, but it's possibly google blocked this since then.

**Comment by ngunia** [comment]
@emeth- Ah sorry, I didn't mean that the method doesn't have a return, I meant the error occurs in that method.  I added some debug statements before and after [this line](https://github.com/emeth-/pokelocater/blob/master/api/pokelocator_api.py#L361) and it never reached the debug statement after.  This is only true when deployed to heroku, works fine locally.

**Comment by emeth-** [comment]
@ngunia Ah, got it! Thanks, I'll scope it out tonight

**Comment by emeth-** [comment]
@ngunia Did some testing tonight, using fake PTC credentials forced it to fall back to my google credentials.

I was unable to get it to not work - worked every time for me, both locally and on a freshly deployed heroku instance.

Perhaps try redeploying the latest code (I made a bunch of updates) and see if the issue persists.

**Comment by ngunia** [comment]
@emeth- yeah the latest version seems to work, thanks!

**Comment by emeth-** [comment]
Awesome! 

I'm going to close this issue, seems like all issues are either resolved with latest push, or due to the login servers being down earlier (which we can't solve)
