### ISSUE TITLE
System dependencies (postgres, etc)

### ISSUE THREAD

**Issue by hatboysam** [emeth-/pokelocater#7]
In order to get `pip install -r requirements.txt` to work on my Ubuntu machine I had to install a few more dependencies first:

```
sudo apt-get install postgresql
sudo apt-get install libpq-dev
sudo apt-get install python-dev
```

Thought this information could be useful to others.

**Comment by emeth-** [comment]
Thanks! I'll check this out today (and probably going to try to remove the postgres dependency, since we don't use it).

**Comment by emeth-** [comment]
Just removed postgres as a dependency with latest code. With that, going to close this issue for now.      

Thanks!
