### ISSUE TITLE
Maps API quota exceeded

### ISSUE THREAD

**Issue by hatboysam** [emeth-/pokelocater#8]
You have your API key hardcoded into `/static/index.html`, users should be instructed to get their own key and replace it.  RIght now the shared key has exceeded its quota limit and can't be used.

**Comment by ic3guy** [comment]
Yes, I agree with this comment.

**Comment by innocuoussoul** [comment]
Can you make the API key a config var? would make it very nice for heroku

**Comment by ClintOxx** [comment]
yea a config var  would be the only way for heroku users to change it

**Comment by emeth-** [comment]
Excellent idea / comments. I will do so today. In the short term you guys can manually edit your api key into this line/file:
https://github.com/emeth-/pokelocater/blob/master/static/index.html#L33

**Comment by emeth-** [comment]
Latest code now takes the google maps api key as an environment variable, README updated appropriately!
