### ISSUE TITLE
Scans only scan for pokemon north of your location

### ISSUE THREAD

**Issue by KevakaBuel** [emeth-/pokelocater#9]

**Comment by emeth-** [comment]
That... is weird behavior. I'll check it out, but I don't think that's what I was experiencing; is it possible there is only pokemon north of your location?

**Comment by KevakaBuel** [comment]
Maybe. I got it a couple of times, but i will try to varify it when the servers are up again, to see if it is a real problem or if I was just unlucky.

**Comment by ngunia** [comment]
I have the same issue, see here for minor details: [Reddit Thread](https://www.reddit.com/r/pokemongodev/comments/4t3lgh/githubwip_get_precise_location_of_all_nearby/d5f7g2c)

**Comment by KevakaBuel** [comment]
Is there anything with more details, or even code?

**Comment by ngunia** [comment]
Nothing that I could find. I have seen pokemon S/SW/SE but usually < 50m or so, wheras northern directions go as high as 300m.  I'm pretty sure either the server isn't being queried for southern cells, or there is a bug in the processing that skips the southern cells.  I don't really have time to dig deeply into it, but I might later.

**Comment by ngunia** [comment]
So I dug in a little more, I think the issue in calling next() and prev() 10 times each.  It seems that s2sphere follows a hilbert curve, so the navigation doesn't go far enough. I am not sure quite how to accomplish this, but I think a better approach would be to create rectangle/square centered around the GPS locs and provide the id of each cell in that area.

edit: [This blog](http://blog.christianperone.com/2015/08/googles-s2-geometry-on-the-sphere-cells-and-hilbert-curve/) starts with an explanation of hilbert curves and a little more on s2 geometry if someone else wants to give it a crack.

**Comment by emeth-** [comment]
Just pushed code that searches in a cross pattern on your location.

That is, it searches for pokemon in 5 spots. Your position, just north of you, just west, just south, and then just east, and compiles them all together on the map now.

With that, I'm gonna call this issue fixed!

**Comment by KevakaBuel** [comment]
Thank you very much =)

**Comment by emeth-** [comment]
After using the new cross pattern scan for a while last night, I was a bit unimpressed with it. It significantly worsens performance, and had a much much higher error rate. 

Since it did technically work though, I saved the code in a branch called bigger-scan
https://github.com/emeth-/pokelocater/tree/bigger-scan

Ya'll can continue using it there. I'm reverting the main branch back to the smaller scan of just the pokemon in my immediate vicinity, as that best suits my purposes and will get the best performance for people trying out the app for themselves.

**Comment by berend** [comment]
How about making the scan radius a variable?. If servers are down later, I might look into that.

**Comment by adrianocr** [comment]
I back what @berend said. Also @emeth- have you seen https://github.com/TheZ3ro/pkmngo-map? In the main.py file you can set the NUM_STEPS variable to whatever you want and it scans that entire area without issue. Performance is pretty good too (Locally, at least. I haven't tried it on Heroku).
